### ISSUE TITLE
Warning: file_get_contents

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/seoinspector#1]
Ich habe gerade den SeoInspektor in der aktuellen R5 in Kombination mit yrewrite installiert und bekomme folgenden Fehler bei meinem 404 Artikel: 
Warning: file_get_contents(http://xxx.test/404/) [function.file-get-contents]: failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in /xxx/app/redaxo/src/addons/seoinspector/lib/seoinspect.php on line 78
Ich habe einen neuen 404 angelegt, den alten gelöscht, damit war auch der Fehler weg. Dafür hat der neue 404 Artikel nun den Fehler?

**Comment by skerbis** [comment]
äh irgendwie logisch oder? Was für ein Artikel ist das?  😉

**Comment by marcohanke** [comment]
Ich hab in der Kategorie "DomainXY" den Artikel "404" angelegt und den in yrewrite als 404 für die Domain hinterlegt.

**Comment by skerbis** [comment]
Ja und wenn file_get_contents darauf zugreift wirft yrewrite den 404 Fehler. Das ist doch das erwartete Verhalten. Um es smarter zu gestalten müsste seoinspector diesen Artikel ignorieren - denke ich.

**Comment by marcohanke** [comment]
Klingt plausibel. Ich weiß schon was passiert wenn mein Kunde die Fehlermeldung sieht, von daher wäre dein Vorschlag glaube ich ganz gut.

**Comment by skerbis** [comment]
Es ist nur ein Warning / Kein Fehler -  Bekommst du das im Frontend oder Backend?

**Comment by marcohanke** [comment]
Sorry, ein Waring. Im Backend über der Strutkur.

**Comment by skerbis** [comment]
Dann hast du evtl. den Debug-Mode an? ...

**Comment by marcohanke** [comment]
Facepalm und Danke ;-(

**Comment by iceman-fx** [comment]
Hallo,
auch ich bekomme den oben genannten Fehler bei allen Artikeln, sobald ich das XCore-Addon aktiviere und der entsprechende Artikel offline geschalten ist. Der Debug-Modus ist aber aus.

Kann man diese Fehlerausgabe abschalten?

**Comment by iceman-fx** [comment]
Ich habe jetzt einfach mal ein @ vor das file_get_contents in Zeile 78 gesetzt, damit die Ausgabe der Warning nicht mehr kommt.

Wie ich sehe, ist dort auch http:// fest verdrahtet, was mit https-Umleitungen u.U. weitere Probleme machen könnte.

**Comment by skerbis** [comment]
anstelle von  file_get_contents curl verwenden mit CURLOPT_FOLLOWLOCATION
