### ISSUE TITLE
rex_sql_exception

### ISSUE THREAD

**Issue by HassChristian** [FriendsOfREDAXO/seoinspector#11]
Ich hab da ein kleines Problem mit der neuen Version. Sobald ich den Seoinspector aktualisiere bekomme ich nen Whooops mit der Meldung:

Error while executing statement "SELECT rex_module.id, rex_module.name, rex_module.output, rex_module.input, rex_article_slice.*, rex_article.parent_id FROM rex_article_slice LEFT JOIN rex_module ON rex_article_slice.module_id=rex_module.id LEFT JOIN rex_article ON rex_article_slice.article_id=rex_article.id WHERE rex_article_slice.clang_id='1' AND rex_article.clang_id='1' AND rex_article_slice.revision='0' AND rex_article_slice.article_id=1 AND rex_article_slice.status = 1 ORDER BY rex_article_slice.priority"! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'rex_article_slice.status' in 'where clause'

rex: 5.8
yrewrite: 2.5
yförmchen 3.0

LG Christian :-)

**Comment by bloep** [comment]
das Problem kann ich bestätigen
seoinspector Version 0.4

<details>
<summary>System report (REDAXO 5.8.0, PHP 7.2.24-nmm1)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.8.0      |


| PHP           |             |
| ------------: | :---------- |
|       Version | 7.2.24-nmm1 |
|       OPcache | yes         |
|        Xdebug | no          |


| Database      |                            |
| ------------: | :------------------------- |
|       Version | 5.7.26-nmm1-log            |
| Character set | latin1 (latin1_swedish_ci) |


| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |


| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/78.0.3904.108 |
|      Protocol | HTTP/2.0             |
|         HTTPS | yes                  |


| Packages            |             |
| ------------------: | :---------- |
|              backup | 2.4.0       |
|            be_style | 2.8.0       |
| be_style/customizer | 2.8.0       |
|     be_style/redaxo | 2.8.0       |
|      cookie_consent | 3.0.0-beta3 |
|        demo_onepage | 1.2.3       |
|           developer | 3.8.0       |
|                grid | dev         |
|             install | 2.5.0       |
|            markitup | 3.2.0       |
|              mblock | 3.1.0       |
|       media_manager | 2.7.0       |
|  media_manager_plus | 2.0.0       |
|           mediapool | 2.6.0       |
|            metainfo | 2.5.0       |
|           phpmailer | 2.6.0       |
|             project | dev         |
|           structure | 2.8.0       |
|   structure/content | 2.8.0       |
|            tinymce4 | 1.2.1       |
|               users | 2.5.2       |
|               yform | 3.2         |
|          yform/docs | 3.2         |
|         yform/email | 3.2         |
|       yform/manager | 3.2         |
|            yrewrite | 2.6         |
|     yrewrite_scheme | 2.1.3       |

</details>

**Comment by skerbis** [comment]
Version angehoben. Status ist ja Teil des Cores.
