### ISSUE TITLE
Fehler: Field "rex_module.key" does not exist in result

### ISSUE THREAD

**Issue by bepixeld** [FriendsOfREDAXO/seoinspector#15]
Seit Redaxo 5.10 gibt es den module.key. Dieser muss hier auch in der Abfrage eingefügt werden, da es sonst zu Fehlern kommt:
Warning: Field "rex_module.key" does not exist in result! in redaxo/src/core/lib/sql/sql.php on line 766
Lösung siehe Patch #14

**Comment by eaCe** [comment]
Danke für den PR @bepixeld
