### ISSUE TITLE
seoinspector stört bloecks/status in Frontend

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/seoinspector#4]
Wenn zusätzlich zu seoinspector das bloecks Addon installiert ist, werden Slices - die im Backend Offline sind - im Frontend angezeigt. Sobald seoinspector deaktiviert wird, stellt sich wieder das erwartet Verhalten ein.

Es gibt dazu auch bei bloecks ein Issue: https://github.com/FriendsOfREDAXO/bloecks/issues/43

**Comment by tito-tema** [comment]
Kann ich bestätigen: erst nach deinstallation des seoinspectors wurde offline-Blöcke im Frontend wieder richtig (nicht) angezeigt.

**Comment by cukabeka** [comment]
Kann ich auch bestätigen. Workaround zur Fehlersuche: Cache löschen hilft, dann greift bloecks on/off wieder

**Comment by netzproductions** [comment]
Nach Codeanalyse der Datei /lib/seoinspector.php konnte ich in einem Test Case den Fehler auf den Aufruf der Funktion `rex_var_article::getArticle()` in Zeile 71 und 72 zurückführen. Wenn also für die SEO-Analyse der Quelltext des aktuellen Artikels ausgelesen wird, arbeitet bloecks/status nicht mehr korrekt.
Auch der alternative Einsatz von `$articleCNew = new rex_article_content($article_id , $clang);$articleCNewContent=$articleCNew->getArticle(1);` und anschließender Verwendung von `$articleCNewContent` für die Analyse brachte das gleiche fehlerhafte Ergebnis.

**Comment by netzproductions** [comment]
Nachtrag: `rex_var_article::getArticle()` ist ja nur ein Wrapper für `$article = new rex_article_content($id, $clang);
return $article->getArticle($ctype);`, also liegt das Problem wohl dort..

**Comment by schuer** [comment]
@rokitole Bist du noch aktiv für dieses AddOn und könntest einen Bugfix bereitstellen?

**Comment by cukabeka** [comment]
Danke @netzproductions für die Codeanalyse. Ich wüsste gerade auch keinen anderen Weg. Gibts nicht irgendwie eine Funktion im REX Core bzgl generatedHTML oder ähnlich, die bloecks/status nicht tangiert?

**Comment by schuer** [comment]
Ich bin nicht im Thema, aber nur als Hinweis: Falls es daran liegt, dass seoinspector Artikel im **Backend-Modus** generiert, so dass Bloecks’ Methoden wie Slice On/Off nicht feuern: Cache-Warmup hatte das gleiche Problem und wechselt deswegen zum Generieren in den **Frontend-Modus**, siehe
https://github.com/FriendsOfREDAXO/cache_warmup/blob/62c651f53cad923a2182055a50fb57c6046d7546/boot.php#L55-L61

**Comment by netzproductions** [comment]
@schuer Danke, das hat ad hoc nicht weitergeholfen, aber ich denke, daß es grundsätzlich damit zu tun hat.
Ich habe nun für den Moment eine Lösung gefunden, die jedoch sehr brachial und zudem nicht updatesicher ist: Ich binde die Klassen `rex_article_content_base`, `rex_article_content` und `rex_content_service` lokal als Ableitungen der Originalklassen im seoinspector-Skript ein, und füge in der DB-Slice-Abfrage in `rex_article_content_base_local::getArticle()` fix eine zusätzliche Kondition `status=1` ein, um nur sichtbare Blöcke zu berücksichtigen - so werden die Cache-Dateien an dieser Stelle korrekt generiert.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/seoinspector/releases/tag/0.4
