### ISSUE TITLE
Mit Yrewrite Multidomain Inkompatibel

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/seoinspector#5]
Der Aufruf mit einer Hardcoded HTTP Adresse macht bei mir Probleme
https://github.com/FriendsOfREDAXO/seoinspector/blob/master/lib/seoinspect.php#L78

Ich konnte das Problem lösen, indem ich den Teil komplett entfernt habe. Yrewrite iefert bereits die korrekte Domain mit.

`templatehtmlcontent = '".json_encode(htmlentities(str_replace('\'','"',file_get_contents(rex_article::getCurrent()->getUrl()))))."'`

**Comment by skerbis** [comment]
bitte die 0.4 testen und ggf. PR :-) @cukabeka
