### ISSUE TITLE
Versions-Prüfung verhindert die Installation von YForm 3.0

### ISSUE THREAD

**Issue by greatif** [FriendsOfREDAXO/seoinspector#6]
![installer](https://user-images.githubusercontent.com/8527203/52267499-75ef4300-2939-11e9-9c7b-2b15b1fdeb46.png)
Versions-Prüfung **yform/manager: '^2.0'** verhindert die Installation von YForm 3.0.

**Comment by schuer** [comment]
Good first issue: Version von yform/manager in der `package.yml` erhöhen und testen, ob es damit fehlerfrei funktioniert.

**Comment by fietstouring** [comment]
umgekehrt kann seoinspector bei Yform 3.1.1 auch nicht installiert werden. Gleiche Fehlermeldung!

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/seoinspector/releases/tag/0.4
