### ISSUE TITLE
Exception wegen SERVER_NAME (localhost:20080)

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/seoinspector#7]
**ErrorException:** file_get_contents() [<a href='https://php.net/manual/function.file-get-contents'>function.file-get-contents</a>]: php_network_getaddresses: getaddrinfo failed: Name or service not known
**File:** redaxo/src/addons/seoinspector/lib/seoinspect.php
**Line:** 76

<details>
<summary>Stacktrace</summary>

| Function                              | File                                                          | Line     |
| ------------------------------------- | ------------------------------------------------------------- | -------- |
| rex_error_handler::handleError        |                                                               |          |
| file_get_contents                     | redaxo/src/addons/seoinspector/lib/seoinspect.php             | 76       |
| include                               | redaxo/src/addons/seoinspector/boot.php                       | 21       |
| rex_package->{closure}                | redaxo/src/core/lib/extension.php                             | 45       |
| rex_extension::registerPoint          | redaxo/src/addons/structure/plugins/content/pages/content.php | 454      |
| include                               | redaxo/src/core/lib/packages/package.php                      | 228      |
| rex_package->includeFile              | redaxo/src/core/lib/be/controller.php                         | 474      |
| rex_be_controller::includePath        | redaxo/src/core/lib/be/controller.php                         | 413      |
| rex_be_controller::includeCurrentPage | redaxo/src/core/backend.php                                   | 215      |
| require                               | redaxo/src/core/boot.php                                      | 135      |
| require                               | redaxo/index.php                                              | 9        |

</details>
<details>
<summary>System report (REDAXO 5.8.0-dev, PHP 7.3.0)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.8.0-dev  |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.3.0      |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |                                |
| ------------: | :----------------------------- |
|       Version | 5.5.5-10.4.1-MariaDB-1:10.4.1+maria~bionic |
| Character set | latin1 (latin1_swedish_ci)     |

| Server        |                |
| ------------: | :------------- |
|            OS | Linux          |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.25  |

| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/74.0.3729.157 |
|      Protocol | HTTP/1.1             |
|         HTTPS | no                   |

| Packages          |            |
| ----------------: | :--------- |
|            backup | 2.3.0      |
|          be_style | 2.7.1      |
|   be_style/redaxo | 2.7.0      |
|           bloecks | 1.4.0      |
|  bloecks/cutncopy | 1.4.0      |
| bloecks/dragndrop | 1.4.0      |
|    bloecks/status | 1.4.0      |
|         demo_base | 2.6.6      |
|           install | 2.5.0      |
|          markitup | 3.2.0      |
|     media_manager | 2.6.0      |
|         mediapool | 2.5.0      |
|          metainfo | 2.4.0      |
|         phpmailer | 2.5.1      |
|           project | dev        |
|         redactor2 | 4.0.2      |
|      seoinspector | 0.3.1      |
|             sprog | 1.2.0      |
|         structure | 2.7.0      |
| structure/content | 2.7.0      |
|             users | 2.5.2      |
|             yform | 3.1.1      |
|        yform/docs | 3.1.1      |
|       yform/email | 3.1.1      |
|     yform/manager | 3.1.1      |
|          yrewrite | 2.5        |

</details>

![Screenshot 2019-05-19 at 21 02 41](https://user-images.githubusercontent.com/1297466/57986774-768b8f80-7a79-11e9-892b-8f906795ebb4.png)

Der generierte String an der fehlerhaften Stelle schaut so aus:

![Screenshot 2019-05-19 at 21 00 54](https://user-images.githubusercontent.com/1297466/57986789-9c189900-7a79-11e9-8025-52f859bb2dea.png)

**Comment by schuer** [comment]
Ähnliches Problem hier: #5

**Comment by skerbis** [comment]
bitte die 0.4 testen @schuer
