### ISSUE TITLE
Geht es hier weiter?

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/seoinspector#8]
Hallo Ronny (@rokitole),

machst Du hier noch weiter oder sollen wir mal gemeinsam gucken?
Manche Issues wären ja wahrscheinlich schnell gelöst - oder?

LG
Oliver

**Comment by rokitole** [comment]
hey oli,

jup, ich habe hierzu schon viele anfragen bekommen mir zeit dafür freigeschaufelt,
daher geht es hier sehr zeitnah weiter! :)

gruß, ron

**Comment by olien** [comment]
Top. Freu mich drauf!

**Comment by skerbis** [comment]
@rokitole habe die 0.4 getestet. Soweit ich erkennen kann, alles ok. 
Wenn Du release möchtest, spreche mich an.

**Comment by skerbis** [comment]
@olien 0.4 ist raus

**Comment by olien** [comment]
Top! DANKE!
