### ISSUE TITLE
Extra Angaben für Open Graph und Twitter Cards ermöglichen?

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/seoinspector#9]
So machte es das YOAST Plugin für WP

![image](https://user-images.githubusercontent.com/330516/60663640-12bdfa00-9e60-11e9-9303-1a668feef97a.png)

![image](https://user-images.githubusercontent.com/330516/60663650-1c476200-9e60-11e9-904a-a65bc60331b3.png)

**Comment by skerbis** [comment]
ist das nicht eher was für XCORE oder sowas? Der Inspektor will ja nur Tipps geben.

**Comment by eaCe** [comment]
Kommt das nicht inzwischen von yrewrite?

**Comment by skerbis** [comment]
in der nächsten YRewrite-Version
